[package]
name = "rapi_py"
version = "0.1.0"
authors = ["Bastien Orivel <eijebong@bananium.fr>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cpython = { git="https://github.com/dgrunwald/rust-cpython.git", features=["python3-sys"] }
rapi = { path = "../rapi" }
