[workspace]
members = [
    "rapi",
    "rapi_codegen"
]

[profile.release]
lto = true
codegen-units = 1


[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["32-columns-tables"] }
diesel_derives = { git = "https://github.com/diesel-rs/diesel.git" }
