[package]
name = "rapi_codegen"
version = "0.1.0"
authors = ["Bastien Orivel <eijebong@bananium.fr>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.11", features = ["aster"] }
quote = "0.3.12"
